### ISSUE TITLE
State and RGB-Lights 

### ISSUE THREAD

**Issue by HansWurst90** [norman-thomas/homebridge-particle-io#11]
Hi,
I just started tinkering with Homebridge and after I found your plugin I played around a little with my photon.
After trying out a few things with it I have two questions.

**Is there a way to tell Homebridge wich state the "ParticleLamp" is in?**
The HomeKit Screen and Siri seem not to be able to know the state of the lamp.
When I ask Siri if the Lamp is on she always tells me its off and Homebrige logs this:
`Calling function: " https://api.particle.io/v1/devices/DEVICEID/onoff " with arg:  ?
`
Is the plugin expecting a certain return value from the onoff-function when using "?" as the state parameter?

**Are you planning to implement RGB-Accessory?**
Instead of on/off it would be really cool if RGB would work.
[Here](https://github.com/EdJoPaTo/homebridge-fake-rgb/blob/master/index.js) is a Fake/Dummy-RGB accessory.
I will look into that a little closer the next days. I just thought you might be interestet.

**Comment by norman-thomas** [comment]
Hi Jan,
as for RGB, someone already made that suggestion in #9. That's definitely on my own wish list. Realistically speaking, though, I can't tell yet when I will have the time to implement it.

Regarding the state, the particle device would need to return `1` when it's powered on and `0` when it's off. The corresponding Arduino / Particle code can be found [here](https://github.com/norman-thomas/epson-projector-remote). I, for example, use it to control my projector.

**Comment by HansWurst90** [comment]
Hi,
thank's for your quick reply. I assumed it would need to return the state but apparently there was an error in my code. So that's on me 😄 .
I will see. Maybe I'll give the RGB a try when I gained enough insight in how the Plugins work exactly.

**Comment by norman-thomas** [comment]
I intend to refactor the `Accessory` in a way that all of them can accept multiple `CharacteristicType` (as an array), which can be configured individually in the `config.json` (with different URLs, parameters, etc for each `Characteristic`). Hopefully in a way, that will make it easily understandable how to configure the plugin.

**Comment by HansWurst90** [comment]
Sounds great. I'm definitely excited for that. 👍

**Comment by jakeholland** [comment]
I have a PR up here https://github.com/norman-thomas/homebridge-particle-io/pull/12 that adds support for RGB and dimmable lights

**Comment by matthieunelmes** [comment]
@jakeholland tried testing. I'm adding device type as "dimmablelightbulb" in the config.json, but when homebridge loads, the device isn't shown in the list of particle devices?

Any ideas?

**Comment by jakeholland** [comment]
To be honest, I have only tested the full RGB color / dimmable light so far. I will test the dimmable one and see what is going on. You will need a "power" and a "brightness" Particle function. Then either a value will pass through or a "?". You should return the current value with the "?" param and the passed in value for the normal call.

    int brightnessState(String args) {
        if (args != "?") {
            brightness = args.toInt();
           setLeds();
        }
        return brightness;
    }

**Comment by matthieunelmes** [comment]
Apologies, I did actually mean the colorlightbulb. But have had luck with neither. I'll try adding those Particle functions now

**Comment by jakeholland** [comment]
I can post my particle sketch if that will help, I just tested the dimmablelightbulb and it is also working. 😄

**Comment by matthieunelmes** [comment]
Yes please!!!

**Comment by matthieunelmes** [comment]
Also, config.json might be helpful

**Comment by jakeholland** [comment]
Here is my config.json:
```
"platforms": [
        {
            "platform": "ParticleIO",
            "name": "Particle Devices",
            "access_token": "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "cloud_url": "https://api.particle.io/v1/devices/",
            "devices": [
              {
                "name": "RGB Light",
                "type": "colorLightbulb",
                "device_id": "XXXXXXXXXXXXXXXXXXXX"
          }
        ]
      }
    ],
```

**Comment by jakeholland** [comment]
Here is an example Particle sketch. I have modified my original code to use the built in RGB LED on the board.

```c++
int hue = 0; 
int saturation = 0;
int brightness = 100;
bool isOn = true;

void setup() {
    RGB.control(true);
    RGB.color(255, 255, 255);
    Particle.function("power", powerState);
    Particle.function("hue", hueState);
    Particle.function("saturation", saturationState);
    Particle.function("brightness", brightnessState);
}

void loop() {
    
}

int powerState(String args) {
    if (args == "?") {
        if (isOn) {
            return 1;
        } else {
            return 0;
        }
    }
    
    int onOff = args.toInt();
    if (onOff != isOn) {
        isOn = (1 == onOff);
        setLeds();
    }
    return onOff;
}

int brightnessState(String args) {
    if (args != "?") {
        brightness = args.toInt();
        setLeds();
    }
    
    return brightness;
}

int hueState(String args) {
    if (args != "?") {
        hue = args.toInt();
        setLeds();
    }
    
    return hue;
}

int saturationState(String args) {
    if (args != "?") {
        saturation = args.toInt();
        setLeds();
    }
    
    return saturation;
}

void setLeds() {
    if (!isOn) {
        RGB.color(0, 0, 0);
    } else {
        byte rgb[3];
        hsvToRgb(rgb);
        RGB.color(rgb[0], rgb[1], rgb[2]);
    }
}

void hsvToRgb(byte rgb[]) {
    double r, g, b;
    
    double h = hue / 360.0;
    double s = saturation / 100.0;
    double v = brightness / 100.0;

    int i = int(h * 6);
    double f = h * 6 - i;
    double p = v * (1 - s);
    double q = v * (1 - f * s);
    double t = v * (1 - (1 - f) * s);

    switch(i % 6){
        case 0: r = v, g = t, b = p; break;
        case 1: r = q, g = v, b = p; break;
        case 2: r = p, g = v, b = t; break;
        case 3: r = p, g = q, b = v; break;
        case 4: r = t, g = p, b = v; break;
        case 5: r = v, g = p, b = q; break;
    }

    rgb[0] = r * 255;
    rgb[1] = g * 255;
    rgb[2] = b * 255;
}

```

**Comment by matthieunelmes** [comment]
Odd... the accessory Post Light is not appearing on the Particle Devices list when homebridge loads

For some reason it doesn't recognise accessories with colorLightbulb or dimmableLightBulb types 
<img width="578" alt="screen shot 2017-07-17 at 23 33 12" src="https://user-images.githubusercontent.com/5974296/28292759-765ba816-6b48-11e7-9d1e-b24e4535c878.png">

**Comment by jakeholland** [comment]
I would assume your plugin did not properly get updated?

**Comment by matthieunelmes** [comment]
My apologies! I'd cloned the repo and not realised that it hadn't fetched the changes from your RGB branch! 

All working correctly now, doh!
