### ISSUE TITLE
Hue/RGB Lightbulb changes break custom function names

### ISSUE THREAD

**Issue by cbpowell** [norman-thomas/homebridge-particle-io#13]
The changes in the v0.0.9 changes related to Hue and Dimmable lightbulbs appear to break the ability to use custom function names for devices.

As of v0.0.8, the `function_name` value could be set in config.json to specify the Particle function to call for getting/setting state. In my particular use case, I have a single Particle controlling two different lights (via a relay board), so I was using a different function name value for each to allow independent control.

In v0.0.9, the calls to the Particle function have been [changed to a static string](https://github.com/norman-thomas/homebridge-particle-io/blob/f069d8fcfe735cc7a464b6f1af2cf3a29e7e7b63/src/ActorAccessory.js#L37) and the `function_name` config.json value has no effect. There is probably a workaround on the "set" side (by giving the `args` config value a unique prefix), but on the "get" side the call will always be to the "power" function with an argument of "?" - meaning Particle hosting multiple devices can't distinguish which device is being queried.

This may be something @jakeholland wants to check out too, since the changes were mostly brought on by the RGB/dimmable implementation. I haven't yet spent the time to fully comprehend the code flow, but I'd think a solution might be to prefix or suffix the static strings used for hue, power, saturation, etc. with the config.json-specified `function_name` value?

**Comment by jakeholland** [comment]
I ended up removing the configuration as I didn’t see the need for it. It should able to be added back pretty easily though!

**Comment by norman-thomas** [comment]
Hi @cbpowell 
Sorry for that. The `function_name` config parameter was re-activated recently via #19.
Please check whether it works for you now.
I'll close this issue for now, but do complain if it doesn't work for you.

**Comment by cbpowell** [comment]
Awesome - I'll check it out, thanks!
