### ISSUE TITLE
current version does not seem to run user defined particle functions

### ISSUE THREAD

**Issue by scottbots** [norman-thomas/homebridge-particle-io#18]
The current version of this plugin does not seem to run the particle functions and arguments as defined in the config.json.  It only seems to run a function call "power".  Is there a way to bring back the functionality that allows you to name the particle function and arguments you would like to call?

**Comment by ricott** [comment]
Noticed the same a while ago. 
(Did a fork where I implemented the support for it)

**Comment by mguntli** [comment]
see #19

**Comment by norman-thomas** [comment]
Hi @scottbots,
Thanks for notifying! And sorry for the delay. I just merged a pull request (#19) which fixes this issue and published a new version 0.0.12.
