### ISSUE TITLE
Temperature sensor not reading correctly

### ISSUE THREAD

**Issue by roamin-ronin** [norman-thomas/homebridge-particle-io#74]
Not sure why this showed up.

**Comment by roamin-ronin** [comment]
Hey All, I am having trouble getting my sensor to read to my HomeKit app.  It keeps just showing 32 degrees.
Here is what my particle console is showing
`tvalue | temperature=73. `

homebridge logs showing 
`[2019-4-3 21:50:44] [Particle Devices] temperature=73. - Home Temperature - temperaturesensor`

So I know the data is coming to homebridge but doesn't seem to be transmitting to my iOS device.

here's my config
```
 {
            "platform": "ParticleIO",
            "access_token": "<<>>",
            "cloud_url": "https://api.particle.io/v1/devices/",
            "devices": [
                {
                    "name": "Home Temperature",
                    "type": "temperaturesensor",
                    "device_id": "<<>>",
                    "event_name": "tvalue",
                    "split_character": ":"
                }
            ],
            "name": "Particle Devices"
        }
```

**Comment by cody-code-wy** [comment]
I had the same issue, after reading through the code I found that for some reason the SensorAccessory class expects a device.key property to split the results from the event.

Try adding this after the split_character line
```
"key": "true"
```

additionally you will have some issues because you have split_character set to ":" when you are using "=" on the event. So you should either change that, or remove the line in your config.


So the correct config may look something like
```
{
            "platform": "ParticleIO",
            "access_token": "<<>>",
            "cloud_url": "https://api.particle.io/v1/devices/",
            "devices": [
                {
                    "name": "Home Temperature",
                    "type": "temperaturesensor",
                    "device_id": "<<>>",
                    "event_name": "tvalue",
                    "split_character": "=",
                    "key": "true"
                }
            ],
            "name": "Particle Devices"
        }
```

**Comment by roamin-ronin** [comment]
Ah that seems to fix it. I had tried the split character but not with the key:true.

Also, it only seems to use C so my house was apparently 158 degrees. :)   thanks for that!
